import React, { useEffect, useState } from 'react';
import { interviewApi } from '../services/api';
import confetti from 'canvas-confetti';
import { Award, CheckCircle, AlertTriangle, Calendar, ArrowLeft, Download, Sparkles, Target, Zap } from 'lucide-react';

export default function ReportPage({ sessionId, onBackToDashboard }) {
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchReport();
    confetti({
      particleCount: 80,
      spread: 70,
      origin: { y: 0.6 }
    });
  }, [sessionId]);

  const fetchReport = async () => {
    try {
      const res = await interviewApi.getSessionDetails(sessionId);
      setReportData(res.data);
    } catch (err) {
      console.error("Error fetching report:", err);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div style={{ textAlign: 'center', padding: '80px', color: 'var(--primary)' }}>
        Generating Comprehensive AI Scorecard & 4-Week Roadmap...
      </div>
    );
  }

  const { session, final_report, questions, responses } = reportData || {};
  const report = final_report || {};

  const overallScore = report.overallScore ?? session?.overallScore ?? 0;
  const technicalScore = report.technicalScore ?? 0;
  const communicationScore = report.communicationScore ?? 0;
  const problemSolvingScore = report.problemSolvingScore ?? 0;
  const hiringRecommendation = report.hiringRecommendation || (overallScore === 0 ? "No Hire / Incomplete" : "Hire");

  const topStrengths = report.topStrengthsJson ? JSON.parse(report.topStrengthsJson) : (overallScore === 0 ? ["Session attempted"] : []);
  const areasToImprove = report.areasToImproveJson ? JSON.parse(report.areasToImproveJson) : (overallScore === 0 ? ["Provide technical answers to question prompts"] : []);
  const roadmap = report.actionableRoadmapJson ? JSON.parse(report.actionableRoadmapJson) : [];

  const getScoreColor = (sc) => sc >= 75 ? '#34d399' : sc >= 40 ? '#f59e0b' : '#f43f5e';

  return (
    <div style={{ maxWidth: '1000px', margin: '0 auto', padding: '32px 24px' }}>
      {/* Back Button */}
      <button 
        onClick={onBackToDashboard}
        className="btn-secondary"
        style={{ marginBottom: '24px', padding: '8px 16px', fontSize: '0.85rem' }}
      >
        <ArrowLeft size={16} /> Return to Dashboard
      </button>

      {/* Hero Scorecard Banner */}
      <div className="glass-panel glass-panel-glow" style={{
        padding: '40px',
        borderRadius: '24px',
        marginBottom: '32px',
        background: 'linear-gradient(135deg, rgba(99, 102, 241, 0.15), rgba(16, 185, 129, 0.1))',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: '24px'
      }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px' }}>
            <span className="badge-pill badge-emerald">Interview Completed</span>
            <span className="badge-pill badge-indigo">{session?.role}</span>
          </div>
          <h1 style={{ fontSize: '2.25rem', fontWeight: 800, marginBottom: '8px' }}>
            Performance Scorecard & Roadmap
          </h1>
          <p style={{ color: 'var(--text-muted)', maxWidth: '550px', fontSize: '0.95rem' }}>
            {report.summaryVerdict || (overallScore === 0 ? "Candidate did not provide valid technical answers to the interview questions." : "Detailed technical evaluation generated by LangGraph multi-agent analysis.")}
          </p>
        </div>

        <div style={{
          textAlign: 'center',
          background: 'rgba(10, 15, 26, 0.7)',
          padding: '24px 32px',
          borderRadius: '20px',
          border: '1px solid var(--border-glass-glow)'
        }}>
          <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', fontWeight: 600, textTransform: 'uppercase' }}>
            Overall Score
          </span>
          <div style={{ fontSize: '3rem', fontWeight: 800, color: getScoreColor(overallScore), lineHeight: 1.1 }}>
            {overallScore}
            <span style={{ fontSize: '1.25rem', color: 'var(--text-dim)' }}>/100</span>
          </div>
          <span className="badge-pill badge-purple" style={{ marginTop: '8px', display: 'inline-block' }}>
            Recommendation: {hiringRecommendation}
          </span>
        </div>
      </div>

      {/* Metrics Breakdown Grid */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
        gap: '20px',
        marginBottom: '32px'
      }}>
        <div className="glass-panel" style={{ padding: '24px' }}>
          <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem', fontWeight: 600, marginBottom: '8px' }}>
            Technical Depth
          </div>
          <div style={{ fontSize: '2rem', fontWeight: 800, color: getScoreColor(technicalScore) }}>
            {technicalScore}%
          </div>
          <div style={{ width: '100%', height: '6px', background: 'rgba(255, 255, 255, 0.1)', borderRadius: '3px', marginTop: '10px' }}>
            <div style={{ width: `${technicalScore}%`, height: '100%', background: getScoreColor(technicalScore), borderRadius: '3px' }} />
          </div>
        </div>

        <div className="glass-panel" style={{ padding: '24px' }}>
          <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem', fontWeight: 600, marginBottom: '8px' }}>
            Communication Clarity
          </div>
          <div style={{ fontSize: '2rem', fontWeight: 800, color: getScoreColor(communicationScore) }}>
            {communicationScore}%
          </div>
          <div style={{ width: '100%', height: '6px', background: 'rgba(255, 255, 255, 0.1)', borderRadius: '3px', marginTop: '10px' }}>
            <div style={{ width: `${communicationScore}%`, height: '100%', background: getScoreColor(communicationScore), borderRadius: '3px' }} />
          </div>
        </div>

        <div className="glass-panel" style={{ padding: '24px' }}>
          <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem', fontWeight: 600, marginBottom: '8px' }}>
            Problem Solving & Architecture
          </div>
          <div style={{ fontSize: '2rem', fontWeight: 800, color: getScoreColor(problemSolvingScore) }}>
            {problemSolvingScore}%
          </div>
          <div style={{ width: '100%', height: '6px', background: 'rgba(255, 255, 255, 0.1)', borderRadius: '3px', marginTop: '10px' }}>
            <div style={{ width: `${problemSolvingScore}%`, height: '100%', background: getScoreColor(problemSolvingScore), borderRadius: '3px' }} />
          </div>
        </div>
      </div>

      {/* Strengths vs Improvements */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px', marginBottom: '32px' }}>
        <div className="glass-panel" style={{ padding: '28px' }}>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#34d399', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <CheckCircle size={20} /> Highlighted Technical Strengths
          </h3>
          <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {topStrengths.map((st, i) => (
              <li key={i} style={{
                background: 'rgba(16, 185, 129, 0.1)',
                border: '1px solid rgba(16, 185, 129, 0.2)',
                padding: '12px 16px',
                borderRadius: '10px',
                fontSize: '0.9rem',
                color: '#d1fae5'
              }}>
                ✓ {st}
              </li>
            ))}
          </ul>
        </div>

        <div className="glass-panel" style={{ padding: '28px' }}>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#818cf8', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Target size={20} /> Priority Focus Areas
          </h3>
          <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {areasToImprove.map((imp, i) => (
              <li key={i} style={{
                background: 'rgba(99, 102, 241, 0.1)',
                border: '1px solid rgba(99, 102, 241, 0.2)',
                padding: '12px 16px',
                borderRadius: '10px',
                fontSize: '0.9rem',
                color: '#e0e7ff'
              }}>
                💡 {imp}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Actionable 4-Week Learning Roadmap */}
      <div className="glass-panel" style={{ padding: '32px', marginBottom: '32px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '24px' }}>
          <div style={{ width: '40px', height: '40px', borderRadius: '12px', background: 'rgba(139, 92, 246, 0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Zap size={22} color="#c084fc" />
          </div>
          <div>
            <h3 style={{ fontSize: '1.25rem', fontWeight: 800 }}>Personalized 4-Week Mastery Roadmap</h3>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Generated by AI based on identified skill gaps</span>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px' }}>
          {roadmap.map((item, idx) => (
            <div key={idx} style={{
              background: 'rgba(10, 15, 26, 0.6)',
              border: '1px solid var(--border-glass)',
              borderRadius: '14px',
              padding: '20px'
            }}>
              <span className="badge-pill badge-purple" style={{ marginBottom: '8px', display: 'inline-block' }}>
                Week {item.week || idx + 1}
              </span>
              <h4 style={{ fontSize: '0.95rem', fontWeight: 700, marginBottom: '6px' }}>{item.topic}</h4>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', lineHeight: 1.4 }}>{item.task}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
